/*
 * default_config.h - Embedded fallback zelda3.ini template.
 *
 * This header gives the executable enough information to recreate zelda3.ini
 * when no shipped or explicit default config is available. The shipped
 * zelda3.ini remains the primary template for packaged builds; this copy is
 * only a last-resort bootstrap.
 */
#ifndef ZELDA3_DEFAULT_CONFIG_H_
#define ZELDA3_DEFAULT_CONFIG_H_

/* Default INI text written to the selected user/config path when zelda3.ini is
 * absent. Values mirror the repository's zelda3.ini defaults so a recreated
 * file starts the game with the same audio, video, feature, keyboard, and
 * gamepad behavior.
 */
static const char kDefaultZelda3Ini[] =
  "# zelda3.ini was recreated because no default config file was present.\n"
  "# Edit this file to change local graphics, sound, feature, keyboard, and gamepad settings.\n"
  "\n"
  "[General]\n"
  "Autosave = 0\n"
  "DisplayPerfInTitle = 0\n"
  "ExtendedAspectRatio = 16:9\n"
  "FillExtendedAspectRatioBorders = 1\n"
  "DisableFrameDelay = 0\n"
  "\n"
  "[Graphics]\n"
  "WindowSize = Auto\n"
  "Fullscreen = 0\n"
  "WindowScale = 3\n"
  "NewRenderer = 1\n"
  "EnhancedMode7 = 1\n"
  "IgnoreAspectRatio = 0\n"
  "NoSpriteLimits = 1\n"
  "OutputMethod = OpenGL\n"
  "LinearFiltering = 0\n"
  "Shader =\n"
  "DimFlashes = 0\n"
  "\n"
  "[Sound]\n"
  "EnableAudio = 1\n"
  "AudioFreq = 44100\n"
  "AudioChannels = 2\n"
  "AudioSamples = 512\n"
  "EnableMSU = false\n"
  "MSUPath = msu/alttp_msu-\n"
  "ResumeMSU = 1\n"
  "MSUVolume = 100%\n"
  "\n"
  "[Features]\n"
  "ItemSwitchLR = 1\n"
  "ItemSwitchLRLimit = 0\n"
  "TurnWhileDashing = 0\n"
  "MirrorToDarkworld = 0\n"
  "CollectItemsWithSword = 0\n"
  "BreakPotsWithSword = 0\n"
  "DisableLowHealthBeep = 0\n"
  "RearrangeHUD = 1\n"
  "HUDMagicFramePosition = 0,0\n"
  "HUDMagicMeterPosition = 0,0\n"
  "HUDItemBoxPosition = 3,0\n"
  "HUDItemIconPosition = 4,1\n"
  "HUDItemXBoxPosition = 7,0\n"
  "HUDItemXIconPosition = 8,1\n"
  "HUDItemLBoxPosition = 3,4\n"
  "HUDItemLIconPosition = 4,5\n"
  "HUDItemRBoxPosition = 7,4\n"
  "HUDItemRIconPosition = 8,5\n"
  "HUDRupeesBackdropPosition = 0,26\n"
  "HUDRupeesPosition = 3,26\n"
  "HUDBombsBackdropPosition = 7,26\n"
  "HUDBombsPosition = 9,26\n"
  "HUDArrowsBackdropPosition = 11,26\n"
  "HUDArrowUpgradeBackdropPosition = 11,26\n"
  "HUDArrowsPosition = 13,26\n"
  "HUDKeysBackdropPosition = 15,26\n"
  "HUDKeysPosition = 16,26\n"
  "HUDFloorIndicatorPosition = 31,3\n"
  "HUDHeartsFramePosition = 38,1\n"
  "HUDHeartMeterPosition = 38.5,2\n"
  "SkipIntroOnKeypress = 0\n"
  "ShowMaxItemsInYellow = 0\n"
  "MoreActiveBombs = 0\n"
  "CarryMoreRupees = 1\n"
  "MiscBugFixes = 0\n"
  "GameChangingBugFixes = 0\n"
  "CancelBirdTravel = 0\n"
  "NewSettingsMenu = 1\n"
  "\n"
  "[KeyMap]\n"
  "Controls = Up, Down, Left, Right, Right Shift, Return, x, z, s, a, c, v\n"
  "CheatLife = w\n"
  "CheatKeys = o\n"
  "CheatWalkThroughWalls = Ctrl+e\n"
  "ClearKeyLog = k\n"
  "StopReplay = l\n"
  "Fullscreen = Alt+Return\n"
  "Reset = Ctrl+r\n"
  "Pause = Shift+p\n"
  "PauseDimmed = p\n"
  "Turbo = Tab\n"
  "ReplayTurbo = t\n"
  "WindowBigger = Ctrl+Up\n"
  "WindowSmaller = Ctrl+Down\n"
  "NewSettingsMenu = q\n"
  "VolumeUp = Shift+=\n"
  "VolumeDown = Shift+-\n"
  "Load = F1,F2,F3,F4,F5,F6,F7,F8,F9,F10\n"
  "Save = Shift+F1,Shift+F2,Shift+F3,Shift+F4,Shift+F5,"
  "Shift+F6,Shift+F7,Shift+F8,Shift+F9,Shift+F10\n"
  "Replay = Ctrl+F1,Ctrl+F2,Ctrl+F3,Ctrl+F4,Ctrl+F5,"
  "Ctrl+F6,Ctrl+F7,Ctrl+F8,Ctrl+F9,Ctrl+F10\n"
  "LoadRef = 1,2,3,4,5,6,7,8,9,0,-,=,Backspace\n"
  "\n"
  "[GamepadMap]\n"
  "Controls = DpadUp, DpadDown, DpadLeft, DpadRight, select, Start, B, A, Y, X, Lb, Rb\n"
  "NewSettingsMenu = L2\n";

#endif  // ZELDA3_DEFAULT_CONFIG_H_
